### ISSUE TITLE
Splice fails to start on macOS 10.13.3

### ISSUE THREAD

**Issue by pedromss** [sjl/splice.vim#36]
Following the documentation and then provoking a conflict and running `git mergetool` I get the following error:
```
Error detected while processing function splice#SpliceInit[3]..provider#python#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pedromss/.dotfiles/vim/.vim/plugged/splice.vim/autoload/splice.py", line 19, in SpliceInit
    splice.init()
  File "/Users/pedromss/.dotfiles/vim/.vim/plugged/splice.vim/autoload/splicelib/init.py", line 103, in init
    setlocal_buffers()
  File "/Users/pedromss/.dotfiles/vim/.vim/plugged/splice.vim/autoload/splicelib/init.py", line 62, in setlocal_buffers
    vim.command('set filetype=%s' % filetype)
  File "/usr/local/lib/python2.7/site-packages/neovim/api/nvim.py", line 218, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
NvimError: Vim(normal):E21: Cannot make changes, 'modifiable' is off
```

I use neovim, but I tried it with vim just to see if it interfered. I get the same result.

After that error, if I press enter I see the BASE file and the LOCAL file (horizontally split)

**Comment by Mantisimo** [comment]
I'm getting the same issue in regular vim v8.1

**Comment by karamfil** [comment]
Same here. any update? 😭
